version: '3.9'

services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - php
      - mysql
    volumes:
      - ./:/var/www/vhosts/blacknachos:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    networks:
      - blacknachos

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    environment:
      PHP_MEMORY_LIMIT: '512M'
      COMPOSER_MEMORY_LIMIT: '-1'
    volumes:
      - ./:/var/www/vhosts/blacknachos:cached
    networks:
      - blacknachos

  mysql:
    image: mysql:latest
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - '33060:3306'
    environment:
      MYSQL_DATABASE: blacknachos
      MYSQL_USER: blacknachos
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - blacknachos


networks:
  blacknachos:
    driver: bridge

volumes:
  blacknachos_mysql:
    driver: local