<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByCategory(Category $category = null)
    {
        return $this->findBy(
            $category ? ['category' => $category] : [],
            ['publishedAt' => 'DESC']
        );
    }
}
